apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - common
resources:
  - bases/ecr.services.k8s.aws_pullthroughcacherules.yaml
  - bases/ecr.services.k8s.aws_repositories.yaml
